- name: create directory /opt/zookeeper
  file: path=/opt/zookeeper state=directory

- name: install zookeeper
  unarchive: src=zookeeper-3.4.12.tar.gz dest=/opt/zookeeper/
  tags:
    - install

- name: create directory /opt/zookeeper/zkdata
  file: path=/opt/zookeeper/zkdata state=directory

- name: create directory /opt/zookeeper/zkdatalog
  file: path=/opt/zookeeper/zkdatalog state=directory

- name: install configuration file
  template: src=zoo.cfg.j2 dest=/opt/zookeeper/zookeeper-3.4.12/conf/zoo.cfg
  tags:
  - config

- name: add myid file
  shell: echo {{ myid }} > /opt/zookeeper/zkdata/myid
  tags:
  - config

  #- name: copy script to clear zookeeper logs.
  #  copy: src=clean_zklog.sh dest=/usr/local/zookeeper-3.4.12/clean_zklog.sh mode=755
  #- name: crontab task
  #  cron: name="clear zk logs" weekday="0" hour="0" minute="0" job="/usr/local/zookeeper-3.4.12/clean_zklog.sh"

- name: start zookeeper
  shell: /opt/zookeeper/zookeeper-3.4.12/bin/zkServer.sh start
  tags:
  - start_zookeeper
