- name: create install directory
  file: path={{ install_path }} state=directory

- name: install zookeeper
  unarchive: src={{ zookeeper_package }} dest={{ install_path }}
  tags:
    - install

- name: create directory
  file: path={{ dataDir }} state=directory

- name: create directory
  file: path={{ dataLogDir }} state=directory

- name: install configuration file
  template: src=zoo.cfg.j2 dest={{ install_path }}/zookeeper-{{ zookeeper_version }}/conf/zoo.cfg
  tags:
  - config

- name: add myid file
  shell: echo {{ myid }} > {{ dataDir }}/myid
  tags:
  - config

  #- name: copy script to clear zookeeper logs.
  #  copy: src=clean_zklog.sh dest=/usr/local/zookeeper-3.4.12/clean_zklog.sh mode=755
  #- name: crontab task
  #  cron: name="clear zk logs" weekday="0" hour="0" minute="0" job="/usr/local/zookeeper-3.4.12/clean_zklog.sh"

- name: start zookeeper
  shell: "{{ install_path }}/zookeeper-{{ zookeeper_version }}/bin/zkServer.sh start"
  tags:
  - start_zookeeper
