---
- name: create necessary catalog
  file: path={{ item }} state=directory
  with_items:
    - "{{ install_path }}"

- name: install filebeat
  unarchive: src={{ filebeat_package }} dest={{ install_path }}

- name: install configuration file
  template: src={{ configuration_template }} dest={{ install_path }}/filebeat-{{ filebeat_version }}-linux-x86_64/filebeat.yml
  # notify: restart filebeat
  tags:
    - config

- name: start filebeat
  shell: "{{ install_path }}/filebeat-{{ filebeat_version }}-linux-x86_64/filebeat -e -c {{ install_path }}/filebeat-{{ filebeat_version }}-linux-x86_64/filebeat.yml"
  tags:
    - start_filebeat
