- hosts: jdk_servers
  remote_user: root
  roles:
  - jdk8
  vars:
    - fixed:
    - dynamic:
        jdk_package: jdk-8u171-linux-x64.tar.gz
        env_file: /etc/profile.d/java_env.sh
        jdk_version: 1.8.0_171
