- hosts: kafka_servers
  remote_user: root
  roles:
  - kafka
  vars:
    - fixed:
    - dynamic:
        kafka_version: kafka_2.12-1.1.0
        install_dir: /opt/kafka
        kafka_manager_ip: 10.0.0.11
        listeners_PORT: 9092
        num_network_threads: 3
        num_io_threads: 8
        log_dirs: /opt/kafka/kafka-logs
        num_partitions: 1
        num_recovery_threads_per_data_dir: 1
        zookeeper_connect: 10.0.0.11:12181,10.0.0.12:12181,10.0.0.13:12181
