- name: restart kafka
  shell: "{{ install_dir }}/{{ kafka_version }}/bin/kafka-server-stop.sh; \
  {{ install_dir }}/{{ kafka_version }}/bin/kafka-server-start.sh -daemon {{ install_dir }}/{{ kafka_version }}/config/server.properties"
