#========修改 metricbeat 配置文檔========
#複製「metricbeat」
  - name: 複製「metricbeat-6.3.0」 
    copy: src='/opt/metricbeat-6.3.0-linux-x86_64.tar.gz' dest='/opt/'
#解壓縮「metricbeat」
  - name: 解壓縮 「metricbeat-6.3.0-linux-x86_64.tar.gz」 指定「/opt」 位置
    shell: tar -C /opt/ -zvxf /opt/metricbeat-6.3.0-linux-x86_64.tar.gz
#========修改 metricbeat.yml 配置文檔========
#=停止輸出「elasticsearch output」===
  - name: 修改 metricbeat.yml 配置文檔
    shell: sed -i 's/output.elasticsearch:/#output.elasticsearch:/' /opt/metricbeat-6.3.0-linux-x86_64/metricbeat.yml
  - name: 修改 metricbeat.yml 配置文檔
    shell: sed -i 's/hosts:\s\["localhost:9200"\]/#hosts:\ \["localhost:9200"\]/g' /opt/metricbeat-6.3.0-linux-x86_64/metricbeat.yml
#========修改 metricbeat.yml 配置文檔========
#=輸出「Logstash output」===
  - name: 修改 metricbeat.yml 配置文檔
    shell: sed -i 's/#output.logstash:/output.logstash:/' /opt/metricbeat-6.3.0-linux-x86_64/metricbeat.yml
  - name: 修改 metricbeat.yml 配置文檔
    shell: sed -i 's/#hosts:\s\["localhost:5044"\]/hosts:\ \["{{ip_address}}:{{ip_port}}"\]/g' /opt/metricbeat-6.3.0-linux-x86_64/metricbeat.yml
#========「nohup」後台執行「metricbeat」=====
#背景執行「metricbeat」會讀取「metricbeat.yml」設定檔
  - name: 背景執行「metricbeat」會讀取「metricbeat.yml」設定檔
    shell: nohup /opt/metricbeat-6.3.0-linux-x86_64/metricbeat -e -c /opt/metricbeat-6.3.0-linux-x86_64/metricbeat.yml >/dev/null 2>&1 &
#========「檢查」後台「metricbeat」PID=====
  - name: check_metricbeat_pid
    shell: ps -ef | grep "metricbeat"
    #使用「register」紀錄「結果」
    register: metricbeat_pid
  - name: print metricbeat_pid
    debug:
    #顯示「紀錄結果」
     msg: "{{ metricbeat_pid }}"