- name: create directory for elasticsearch data
  file: dest="{{ path_data }}" mode=0755 state=directory

- name: install elasticsearch
  # unarchive module owner and group only effect on directory.
  unarchive: src={{ es_package }} dest={{ install_path }}

# - name: install memory configuration file for elasticsearch
  # template: src=elasticsearch.in.sh.j2 dest={{ install_path }}/elasticsearch-{{ es_version }}/bin/elasticsearch.in.sh
  # tags:
  # - config

- name: install configuration file for elasticsearch
  template: src=elasticsearch.yml.j2 dest={{ install_path }}/elasticsearch-{{ es_version }}/config/elasticsearch.yml
  tags:
  - config

- name: install unzip package
  yum: name=unzip state=present
  tags:
  - install_unzip

- name: create directory for elasticsearch-analysis-ik plugin
  file: dest={{ install_path }}/elasticsearch-{{ es_version }}/plugins/ik mode=0755 state=directory
  tags:
  - install_ik

- name: copy and unizp elasticsearch-analysis-ik plugin
  unarchive: src=elasticsearch-analysis-ik-6.3.0.zip dest={{ install_path }}/elasticsearch-{{ es_version }}/plugins/ik
  tags:
  - install_ik

- name: start elasticsearch
  shell: "{{ install_path }}/elasticsearch-{{ es_version }}/bin/elasticsearch -d -p /tmp/es.pid"
  # "cmd": "/home/deploy/elk/elasticsearch/elasticsearch-6.3.0/bin/elasticsearch -d -p /tmp/es.pid"
  register: result
  tags:
  - start_elasticsearch

- name: show start_elasticsearch result
  debug: var=result
  tags:
  - start_elasticsearch
